### PR TITLE
events now have a cover image and properties

### PR DESCRIPTION
**Pull request by pmadruga**
Now the events fetch a cover object with the format (example):

"cover": {
        "offset_y": 53,
        "id": "919893354727777",
        "offset_x": 0,
        "source": "https://scontent.xx.fbcdn.net/hphotos-xtf1/t31.0-8/s720x720/11043135_919893354727777_8372358436329231302_o.jpg",
        "cover_id": "919893354727777"
      },

### CODE REVIEW

**Comment by tobilg** [comment]
Makes sense to me. Thanks.

**Comment by pmadruga** [comment]
Thank you. Your project is awesome - I have been playing with it for some time now.

**Comment by tobilg** [comment]
Thanks again. Please note that the events themselves will not contain a cover image with your commit, but only the venues. Is that what you wanted?

**Comment by pmadruga** [comment]
It makes sense to have both. The issue is that I can fetch pictures of the events (by adding "picture" to the "events.fields"), but by default the images are sized 50x50. The api allows to fetch a custom height and width, but I want to do it without hacky solutions. Have any ideas?

**Comment by tobilg** [comment]
According to https://developers.facebook.com/docs/graph-api/reference/event/picture/ it is possible to add `picture.type(large)`...

**Comment by tobilg** [comment]
I commited a new version, including the picture fields.

**Comment by pmadruga** [comment]
Right. Thanks.

**Pull request merged**
